# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('light', models.FloatField()),
                ('ambient_temp', models.FloatField()),
                ('radiant_temp', models.FloatField()),
                ('humidity', models.FloatField()),
                ('x_airflow', models.FloatField()),
                ('z_airflow', models.FloatField()),
                ('sound_level', models.FloatField()),
                ('x_pos', models.FloatField()),
                ('y_pos', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('ave_light', models.FloatField()),
                ('ave_ambient_temp', models.FloatField()),
                ('ave_radiant_temp', models.FloatField()),
                ('ave_humidity', models.FloatField()),
                ('ave_x_airflow', models.FloatField()),
                ('ave_z_airflow', models.FloatField()),
                ('ave_sound_level', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RatingMeasurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comfort.Measurement')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comfort.Rating')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(choices=[('BB', 'Brown'), ('MZ', 'Marquez'), ('SH', 'Stratton')], max_length=2)),
                ('roomnumber', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RoomRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Date Measured')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comfort.Rating')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comfort.Room')),
            ],
        ),
    ]
