# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-13 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comfort', '0002_room_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='roomscript',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
