# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-20 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comfort', '0003_room_roomscript'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratingmeasurement',
            name='measurement',
        ),
        migrations.RemoveField(
            model_name='ratingmeasurement',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='csvfile',
            field=models.FileField(null=True, upload_to='csvs/'),
        ),
        migrations.DeleteModel(
            name='Measurement',
        ),
        migrations.DeleteModel(
            name='RatingMeasurement',
        ),
    ]
